Iter13
gostuding/go-metrics pull request #15
Opened 2023-06-11 18:32 UTC by gostuding

2023-06-12 22:21 UTC, s-shpak requested changes

2023-06-12 22:21 UTC, s-shpak commented on internal/server/handlers.go
> +				return "", errors.New("context done error")
Здесь можно вернуть `ctx.Err()`

2023-06-12 22:21 UTC, s-shpak commented on internal/server/handlers.go
> +	// value, err := storage.GetMetric(request.Context(), metric.mType, metric.mName)
deadcode

2023-06-12 22:21 UTC, s-shpak commented on internal/server/handlers.go
> +	// value, err := storage.UpdateJSON(request.Context(), data)
deadcode

2023-06-12 22:21 UTC, s-shpak commented on internal/server/handlers.go
> +		logger.Warnf("write data to clie`nt error: %w", err)
```suggestion
		logger.Warnf("write data to client error: %w", err)
```

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +				return fmt.Sprint(val), nil
Лучше использовать `strconv.FormatFloat`

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) PingDB(ctx context.Context) error {
Если ты используешь `memStorage`, а не `postgres`, то это может быть просто пустой метод (возвращающий всегда nil)

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +	context, cansel := context.WithTimeout(ctx, 500*time.Millisecond)
Это очень короткий контекст, выставь его хотя бы в 10 секунд

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +func (ms *SQLStorage) updateCounter(ctx context.Context, name string, value int64, connect SQLQueryInterface) (*int64, error) {
`Update` логику можно написать без нескольких запросов. Посмотри документацию по `RETURNING`: https://postgrespro.ru/docs/postgresql/15/sql-insert

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +	if rows.Err() != nil {
`defer rows.Close()` стоит помещать сразу после проверки ошибки

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +		// return &value, fmt.Errorf("counter update error: %w", err)
deadcode

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +	rows, err := ms.con.QueryContext(ctx, fmt.Sprintf("Select name, value from %s order by name;", table))
`%s` нельзя использовать при построении запроса, т.к. есть угроза SQL-injection

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/sql_storage.go
> +	db, err := sql.Open("pgx", ms.ConnectDBString)
Поключения к БД как правило долгоживущие - инициализируются при старте программы и закрываются при выходе из нее

2023-06-12 22:21 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) saveInDatabase() error {
А зачем этот метод? В ТЗ про него ничего, вроде, не было

2023-06-14 08:57 UTC, gostuding commented on cmd/server/main.go
> +		err = server.RunServer(cfg, storage, logger)
сделал отдельную функцию для проверки ошибки

2023-06-14 09:32 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	client := http.Client{}
Объекдинил с существующей функцией отправки на сервер

2023-06-14 09:37 UTC, gostuding commented on internal/server/handlers.go
> +	// value, err := storage.GetMetric(request.Context(), metric.mType, metric.mName)
Исправлено

2023-06-14 09:37 UTC, gostuding commented on internal/server/handlers.go
> +	// value, err := storage.UpdateJSON(request.Context(), data)
исправлено

2023-06-14 09:38 UTC, gostuding commented on internal/server/handlers.go
> +		logger.Warnf("write data to clie`nt error: %w", err)
исправлено

2023-06-14 09:41 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +				return fmt.Sprint(val), nil
Исправил

2023-06-14 10:20 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +	db, err := sql.Open("pgx", ms.ConnectDBString)
Исправил

2023-06-14 10:21 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +	if rows.Err() != nil {
исправил

2023-06-14 10:25 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) PingDB(ctx context.Context) error {
nil возвращать нельзя, т.к. тогда клиенту придёт StatusOk, а в тестах инкремента 10 есть проверка на подключения с заранее неправильными данными. Хотя, это было актуально до переработки под 13 инкремент. Хотел бы оставить данный функционал как есть. Есть два типа хранилища: память и БД, только память может также работать с БД.

2023-06-14 10:28 UTC, gostuding commented on internal/agent/flags.go
> +		return errors.New("args error: report metric by slice and REPORT_INTERVAL must be diferent")
Исправил.
Искал ошибку, которая приводила к панике сервера. Забыл убрать. Ошибка оказалась связана с отсутствием проверки на значения при отправке списка json. Код подправил.

2023-06-14 10:31 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +	context, cansel := context.WithTimeout(ctx, 500*time.Millisecond)
Исправил на 10 секунд.

2023-06-14 10:47 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +	rows, err := ms.con.QueryContext(ctx, fmt.Sprintf("Select name, value from %s order by name;", table))
Исправил

2023-06-14 20:26 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +func (ms *SQLStorage) updateCounter(ctx context.Context, name string, value int64, connect SQLQueryInterface) (*int64, error) {
Здесь возникли проблемы, реализовать без нескольких запросов:
Необходимо проверять наличие значения для counters и суммировать, соответственно необходимо выполнять запрос SELECT. Пробовал сделать через IF EXISTS ... THEN update ... ELSE insert ... (хотя это тоже минимум два запроса SELECT и INSERT), но как передать параметры name и value вместо $1 и $2 не смог разобраться, т.к. GO постоянно вываливает ошибку `mismatched param and argument count ` 

> DO $do$ BEGIN
		IF EXISTS (select * from counters where name = $1)
		THEN
			update counters set value=(select SUM(hr) from (
				SELECT $2 as hr
				UNION ALL
				select SUM(value) as hr from counters where name=$3)t);
		ELSE
			insert into counters(name, value) values($4, $5);
		END IF;
	END $do$;

Пробовал через (опять же два запроса)
`WITH upd AS ( UPDATE counters SET value = value + $2 WHERE name = $1 RETURNING *)  
INSERT INTO counters SELECT * FROM upd;`
но для создания новой записи тоже не подходит, т.к. запрос выполняется без ошибок, а значения не обновляются и не добавляются.

Соответственно, как сделать обновление данных без минимум двух запросов не могу понять.

2023-06-17 15:17 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) PingDB(ctx context.Context) error {
Мне кажется, что не стоит смешивать хранилище в памяти и в БД: если пользователь не передал `dsn`, то ты импользуешь хранилище в памяти, которое никуда не подключается, потому `PingDB` может просто всегда возвращать nil. Если используешь постгрес,  то там действительно надо вызывать внутренний метод `Ping` и проверять результат

2023-06-17 15:17 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) saveInDatabase() error {
Кажется, что стоит разделить хранилище в памяти и в БД

2023-06-17 16:23 UTC, s-shpak requested changes

2023-06-17 16:23 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +func (ms *SQLStorage) updateCounter(ctx context.Context, name string, value int64, connect SQLQueryInterface) (*int64, error) {
Ты можешь использовать `INSER...ON CONFLICT`, чтобы не вызывать `getCounter`, а только апдейтить значение, если ключ уже существует

2023-06-17 16:23 UTC, s-shpak commented on internal/server/storage/sql_storage.go
> +			_, err := ms.updateCounter(ctx, item.ID, *item.Delta, ms.con)
Забыл написать про это:

Сейчас это не батчинг, это запись данных в БД по очереди. В идеале, ты должен делать фиксированное количество запросов к БД (один, например), которое не должно зависеть от количества отправляемых данных. Для батчинга можно:
1. перейти на `pgx` вместо `db/sql`
2. формировать запрос самому
3. использовать библиотеку типа `sqlx` или `squirrel`

2023-06-17 16:23 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +func (ms *SQLStorage) updateCounter(ctx context.Context, name string, value int64, connect SQLQueryInterface) (*int64, error) {
Кстати, забыл еще сказать о том, что если ты делаешь несколько запросов для выполнения какого-то действия, то есть смысл оборачивать их в транзакцию

2023-06-17 16:23 UTC, s-shpak commented on internal/server/handlers.go
> +type fbe func(context.Context, []byte) ([]byte, error)
В целом, такая реализация ретраев имеет право на существование. Единственное, чего не хватает - хорошего покрытия тестами этой логики. Если интересно, то посмотри как этот  функционал реализован здесь: https://github.com/avast/retry-go

2023-06-17 21:48 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +func (ms *SQLStorage) updateCounter(ctx context.Context, name string, value int64, connect SQLQueryInterface) (*int64, error) {
Переделал

2023-06-17 21:59 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) saveInDatabase() error {
ок

2023-06-17 22:24 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +func (ms *memStorage) PingDB(ctx context.Context) error {
перелелал

2023-06-18 15:08 UTC, gostuding commented on internal/server/handlers.go
> +type fbe func(context.Context, []byte) ([]byte, error)
Добавил тесты.
Использовать дополнительный модуль reply можно, но особой разницы и нужды в этом не вижу. Это может только усложнить код, т.к. необходимо дополнительно разбираться в логике работы модуля. В случае критической необходимости, переделаю на reply, но хотелось бы оставить как есть.

2023-06-18 15:29 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +			_, err := ms.updateCounter(ctx, item.ID, *item.Delta, ms.con)
В задании инкремента речь идёт про отправку клиентом значений батчингом (Научите агент работать с использованием нового API (отправлять метрики батчами)). Также, в теории курса отсутствуют примеры работы батчинга или хотябы определение, что это такое. Определения, которые нашёл в интернете относятся либо к биткам, либо определяют как набор, список. Переделал на изменение данных через транзакцию, а вот как сделать один запрос для изменения и добавления произвольного набора значений в двух таблицах - не понимаю. В данной ситуации требуется дополнительное изучение SQL. Необходимы ссылки на конкретные примеры применения батчинга, когда одним запросом обновляются, либо добавляются данные в разнве таблицы.

2023-06-18 21:05 UTC, s-shpak commented on internal/server/storage/sql_functions.go
> +	UPDATE SET value=(select SUM(hr) from (SELECT $2 as hr UNION ALL select SUM(value) as hr from counters where name=$1)t)
Это сложно, посмотри как можно использовать ключевое слово `EXCLUDED`

2023-06-18 21:05 UTC, s-shpak commented on internal/server/storage/sql_storage.go
> +			_, err := ms.updateCounter(ctx, item.ID, *item.Delta, ms.con)
Никакой магии в батчинге нет: ты просто составляешь один запрос для всех значений `INSERT INTO metrics (name, value) VALUES ('first-name', 42), ('second-name', 43), ..., ('last-name', 12345)`

Вопрос в том, как составить этот запрос. Варианты я расписал. Если брать второй вариант, то надо быть осторожным, чтобы не избежать возможности SQL-инъекции. Если хочешь, возьми 1-1, и обсудим

2023-06-19 18:09 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +func NewSQLStorage(DBconnect string, logger *zap.SugaredLogger) (*SQLStorage, error) {
исправил

2023-06-19 18:11 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +			_, err := ms.updateCounter(ctx, item.ID, *item.Delta, ms.con)
Теперь понятно, это некая аналогия bulk в ElasticSearch.

2023-06-19 21:07 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +			_, err := ms.updateCounter(ctx, item.ID, *item.Delta, ms.con)
Обсудить онлайн не получится, работа не предсказуемо заканчивается, время только ночью остаётся. 
Изменил запись в БД. Добавил проверки названия метрики и их дублировани при передаче списком json.  
Для записи используется два запроса, по одному на таблицу

2023-06-19 21:22 UTC, gostuding commented on cmd/server/main.go
> +	checkForError(err, nil)
Туплю, не могу понять что именно надо. Сделал функцию run, перенёс туда запуск сервера и проверку ошибки

2023-06-20 14:02 UTC, s-shpak requested changes

2023-06-20 19:10 UTC, gostuding commented on internal/server/storage/sql_functions.go
> +		if isTableExist(ctx, key, db) != nil {
Исправил

2023-06-20 19:11 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +	defer sqtx.Rollback()
Взято из теории курса. Сказано, что при успешном comite выполнение этой функции не влияет ни на что. Исправил, RollBack выполняется только при ошибке commit

2023-06-20 19:33 UTC, gostuding commented on cmd/server/main.go
> +	checkForError(err, nil)
Переделал, но понять как проверять ошибку один раз не могу, т.к. при создании логера и чтении параметров необходимо проверять ошибку

2023-06-20 20:36 UTC, gostuding commented on internal/server/storage/sql_storage.go
> +			rs = append(rs, fmt.Sprintf("('%s', %d)", key, value))
Переделал

2023-06-20 22:26 UTC, s-shpak commented on cmd/server/main.go
> +	checkForError(err, nil)
Инициализацию логгера можно оставить в `main`: если произошла ошибка во время нее, то ее можно залогировать стандартным `log`. Далее новый логгер передается в `run` и все остальные ошибки логируются им

2023-06-20 22:41 UTC, gostuding commented on cmd/server/main.go
> +	checkForError(err, nil)
Поправил

2023-06-20 22:52 UTC, s-shpak requested changes

2023-06-20 22:52 UTC, s-shpak commented on cmd/server/main.go
> +		logger.Warn(err)
Лучше `Fatal`, т.к. `Fatal` завершит процесс с кодом `1`, что бывает важно

2023-06-22 18:34 UTC, s-shpak approved these changes

2023-06-22 19:15 UTC, gostuding commented
done

2023-06-22 19:16 UTC, merged