Iter15
gostuding/go-metrics pull request #17
Opened 2023-06-23 22:18 UTC by gostuding

2023-06-29 15:08 UTC, s-shpak requested changes

2023-06-29 15:08 UTC, s-shpak commented on internal/agent/runner.go
> +			go storage.SendMetrics()
Это чревато тем, что если канал отправки забъется (отправление метрик будет медленее получения запросов на отправление), то количество созданных горутин будет расти неконтроллируемо пока приложение не упадет. Это надо как-то исправить

2023-06-29 15:08 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +func (ms *metricsStorage) sendJSONToServer(URL string, body []byte, compress bool, key string, metric *metrics) {
Пока отправляемые данные не подписываются

2023-06-29 15:08 UTC, s-shpak commented on internal/server/handlers.go
> +func mkHash(writer http.ResponseWriter, body []byte, key string) error {
1. Это тоже лучше делать внутри `middleware`
2. Если ты добавляешь подпись к ответу, то клиенту стоит ее проверять при получении

2023-06-29 15:08 UTC, s-shpak commented on internal/server/middleware.go
> +func newHashReader(r *http.Request, key []byte) (*hashReader, error) {
Зачем создавать новую структуру, если она полностью повторяет поведение `bytes.Reader`? Можно вынести проверку хеша в отдельную функцию, а потом просто переиспользовать прочитанное тело запроса (поместив его в новый стандартный ридер)

2023-06-29 20:24 UTC, gostuding commented on internal/agent/flags.go
> +	flag.StringVar(&agentArgs.Key, "k", "", "Key for SHA256")
Добавил поддержку непечатных символов, т.е. параметр Key теперь []byte.

2023-06-29 20:27 UTC, gostuding commented on internal/agent/runner.go
>  		case <-reportTicker.C:
Сделал на основе задания инкремента 12 (Стоит помнить, что: нужно соблюдать обратную совместимость). А так, это помогло выявить несколько критических ошибок в коде при разработке.

2023-06-29 20:28 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +func (ms *metricsStorage) sendJSONToServer(URL string, body []byte, compress bool, key string, metric *metrics) {
Добавил подпись данных. Был уверен, что сделал это раньше, видимо не закомитил.

2023-06-29 20:43 UTC, gostuding commented on internal/agent/runner.go
> +			go storage.SendMetrics()
Добавил проверку возможности отправки данных, проверку наличия места в канале для отправки данных

2023-06-29 21:01 UTC, gostuding commented on internal/server/handlers.go
> +func mkHash(writer http.ResponseWriter, body []byte, key string) error {
Добавил проверку ответа на клиенте

2023-06-29 23:11 UTC, gostuding commented on internal/server/middleware.go
> +func newHashReader(r *http.Request, key []byte) (*hashReader, error) {
В новой структуре есть метод Close, для удовлетворения интерфейсу ReadCloser. Переиспользовать тело запроса при bytes.Reader не получится, т.к. не соответствуют интерфейсы.

2023-06-29 23:19 UTC, gostuding commented on internal/server/handlers.go
> +func mkHash(writer http.ResponseWriter, body []byte, key string) error {
Добавил в middleware. Для избежания "ругательств" от go (superfluous response.WriteHeader call) добавлена переменная для ограничения записи в http.ResponseWriter.WriteHeader.

2023-06-30 08:42 UTC, s-shpak commented on internal/agent/runner.go
>  		case <-reportTicker.C:
Обратную совместимость соблюдать следует, но это значит, что не надо убирать логику хендлеров метрик, которые присылаются по одной, из кода сервера. Так что в текуще реализации агента лучше оставить только способ отправки батчами

2023-06-30 08:43 UTC, s-shpak commented on internal/agent/flags.go
> +	flag.StringVar(&agentArgs.Key, "k", "", "Key for SHA256")
Да, так лучше: даже если сейчас автотесты передают все обычной строкой, то в дальнейшем, возможно, ключ будет передаваться в какой-то кодировке. Тогда код уже будет адаптирован под работу с байтами

2023-06-30 08:54 UTC, s-shpak commented on internal/agent/runner.go
> +			go storage.SendMetrics()
Лучше сделать по другому: ты можешь просто проверить, что канал неполон при помощи `select-default`: если запись в канал невозможна, то просто дропай подготовленный к отправлению пакет (можно с ворнингом).

Почему это лучше чем текущая реализация:
1. Более идиоматический код
2. Текущая реализация не защищает от забивания на 100%: представь, что канал забьется между проверкой, которую ты делаешь и отправлением пакета

2023-06-30 10:20 UTC, s-shpak commented on internal/server/handlers.go
> +func mkHash(writer http.ResponseWriter, body []byte, key string) error {
1. Тебе не надо добавлять новый `reader`, т.к. его логика сводится к проверке хеша боди. Вызови функцию, которая вычитает боди, проверит хеш и запишет боди обратно в `request`
2. Проблема с `superfluous response.WriteHeader call` исходит не из того, что middleware пишет statuscode, а из того, что вызов метода `WriteHeader` всегда должен происходить перед вызовом метода `Write` объекта `http.ResponseWriter`. У тебя это не всегда так (например,в `GetMetric`). Добейся, пожалуйста, корректного поведения без добавления переменной для ограничения записи

2023-06-30 10:20 UTC, s-shpak commented on internal/server/middleware.go
> +func newHashReader(r *http.Request, key []byte) (*hashReader, error) {
См. комментарий выше

2023-07-02 18:50 UTC, gostuding commented on internal/agent/runner.go
>  		case <-reportTicker.C:
Оставил только отправку списком метрик

2023-07-02 20:12 UTC, gostuding commented on internal/server/handlers.go
> +func mkHash(writer http.ResponseWriter, body []byte, key string) error {
1. Переделал под отдельную функцию.
2. Разобрался с предупреждением: проблема связана с повторным вызовом http.ResponseWriter (https://www.programmersought.com/article/90119547039/). Оказывается, при вызове Write автоматически ставится StatusOk если статус не поставлен изначально в коде (прописано в описании функции WriteHeader(int) интерфейса ResponseWriter). Соответственно, необходимо было убрать WriteHeader(http.StatusOk) из кода, т.к. статус уже проставлен. Если ставить код ответа до записи тела ответа, то смысла в middleware нет, т.к. изменение headers ответа после WriteHeader не принимается и хеш отправлен не будет, а до записи тела ответа хеш посчитать нельзя.

2023-07-02 20:45 UTC, gostuding commented on internal/agent/runner.go
> +			go storage.SendMetrics()
Не могу понять как сделать через select-default, сделал проверку через if else перед отправкой одного запроса. Также поменял изменение PollCount при считывании из канала, т.к. за время отправки запроса количество обновлений может поменяться, а приравнивать к нулю будет ошибочно.

2023-07-04 05:36 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +	if len(ms.sendChan) < cap(ms.sendChan) {
Вот как это можно сделать через `select-default`, почитай в доках как это работает (https://go.dev/tour/concurrency/6)

```go
select {
case ms.sendChan <- val:
default:
}
```

2023-07-04 05:36 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +func (ms *metricsStorage) SendMetrics() {
deadcode

2023-07-04 05:36 UTC, s-shpak commented on internal/agent/runner.go
> +			go storage.SendMetrics()
См. Комментарий

2023-07-04 20:19 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +func (ms *metricsStorage) SendMetrics() {
Убрал

2023-07-04 20:19 UTC, gostuding commented on internal/server/flags.go
> +	// Key             string
Убрал

2023-07-04 20:19 UTC, gostuding commented on internal/agent/runner.go
> +			go storage.SendMetrics()
Исправил

2023-07-04 20:27 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	if len(ms.sendChan) < cap(ms.sendChan) {
Исправил. Прежняя логика была ошибочной: переполнение канала было невозможно, т.к. считывание из очереди не зависело от продолжительности запроса. Вместо канала для отправки данных ms.sendChan сделал канал, который считывается только после выполнения запроса к серверу. Таким образом, если запрос будет выполняться продолжительное время, то канал будет заполняться и сработает его переполнение. При отправке изменил if ... else ... на select ... default ...

2023-07-06 10:33 UTC, s-shpak approved these changes

2023-07-06 22:18 UTC, gostuding commented
Sprint 4 done

2023-07-06 22:18 UTC, merged