Iter20
gostuding/go-metrics pull request #20
Opened 2023-09-03 19:21 UTC by gostuding

2023-09-04 06:18 UTC, s-shpak requested changes

2023-09-04 06:18 UTC, s-shpak commented on internal/server/storage/sql_storage.go
Сейчас при локальном запуске тестов без запущенной БД тесты завершаются с ошибкой:

```
Create sql storage error: database ping error: failed to connect to `host=localhost user=postgres database=metrics`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)--- FAIL: Example (0.00s)
got:
Memory storage save success
Create sql storage error: database ping error: failed to connect to `host=localhost user=postgres database=metrics`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
want:
Memory storage save success
SQL storage stop success
--- FAIL: ExampleSQLStorage_Update (0.00s)
got:
SQLStorage ping error
want:
update success
--- FAIL: ExampleSQLStorage_GetMetric (0.00s)
got:
storage clear error: clear gauges table error: failed to connect to `host=localhost user=postgres database=metrics`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
want:
1.100000
--- FAIL: ExampleSQLStorage_UpdateJSON (0.00s)
got:
storage clear error: clear gauges table error: failed to connect to `host=localhost user=postgres database=metrics`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
want:
{"value":1,"id":"metric update json name","type":"gauge"}
--- FAIL: ExampleSQLStorage_UpdateJSONSlice (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x556642]

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc000167c18, {0x0, 0x0}, 0xc0000aaec8?, 0x0, {0x84fa20, 0xc568e0})
	/usr/local/go/src/testing/example.go:95 +0x64a
testing.runExample.func2()
	/usr/local/go/src/testing/run_example.go:59 +0x11c
panic({0x84fa20, 0xc568e0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
database/sql.(*Tx).rollback(0xc0000b55c0?, 0x0?)
	/usr/local/go/src/database/sql/sql.go:2282 +0x22
database/sql.(*Tx).Rollback(0xc000167a58?)
	/usr/local/go/src/database/sql/sql.go:2314 +0x1b
github.com/gostuding/go-metrics/internal/server/storage.(*SQLStorage).UpdateJSONSlice(0xc0000140c8, {0x9880b8, 0xc0000280e0}, {0xc0000d0f50, 0x6a, 0x70})
	/home/bp/go/src/praktikum/github.com/reviews/gostuding/go-metrics/internal/server/storage/sql_storage.go:266 +0x223
github.com/gostuding/go-metrics/internal/server/storage.ExampleSQLStorage_UpdateJSONSlice()
	/home/bp/go/src/praktikum/github.com/reviews/gostuding/go-metrics/internal/server/storage/example_test.go:217 +0x57
testing.runExample({{0x8e9945, 0x21}, 0x915600, {0x8e547a, 0x1a}, 0x0})
	/usr/local/go/src/testing/run_example.go:63 +0x2d0
testing.runExamples(0xc000167dd8, {0xc5efe0?, 0xe, 0xa?})
	/usr/local/go/src/testing/example.go:44 +0x17d
testing.(*M).Run(0xc0000c8000)
	/usr/local/go/src/testing/testing.go:1908 +0x6ef
main.main()
	_testmain.go:97 +0x1aa
FAIL	github.com/gostuding/go-metrics/internal/server/storage	0.019s
FAIL
```

Юнит-тесты предполагают возможность запуска и успешного выполнения без каких-либо внешних зависимостей. Поправь их, пожалуйста, так, чтобы при дефолтном запуске (`go test ./...`) тесты проходили: для этого можно, например, использовать build tags: https://mickey.dev/posts/go-build-tags-testing/

2023-09-04 06:18 UTC, s-shpak commented on staticlint
Не стоит загружать бинарный файл в репозиторий

2023-09-04 06:18 UTC, s-shpak commented on cmd/staticlint/analyzers/osexit/osexit.go
> +			fMain = false
Почему бы при нахождении другого определения функции (не main) просто вызывать `return false` и не выйти из ветви заранее?

2023-09-04 06:18 UTC, s-shpak commented on cmd/staticlint/analyzers/osexit/osexit.go
> +						fn, _ := typeutil.Callee(pass.TypesInfo, x).(*types.Func)
Проверки `type assertion` стоит делать всегда

2023-09-04 18:45 UTC, gostuding commented on staticlint
Удалил

2023-09-04 18:57 UTC, gostuding commented on internal/server/storage/sql_storage.go
Поправил тесты. Внёс описание для запуска тестов в README.
P.S. Попросту не знал как обыграть данную ситуацию. Спасибо за подсказку.

2023-09-04 18:59 UTC, gostuding commented on cmd/staticlint/analyzers/osexit/osexit.go
> +			fMain = false
Поправил.

2023-09-04 19:02 UTC, gostuding commented on cmd/staticlint/analyzers/osexit/osexit.go
> +						fn, _ := typeutil.Callee(pass.TypesInfo, x).(*types.Func)
Поправил.
P.S. Плохо разобрался в данной теме, пока-что это для меня это как серый ящик. Взял код из какого-то другого анализатора. Плохо понимаю, что вообще делает typeutil.

2023-09-05 07:27 UTC, s-shpak requested changes

2023-09-05 07:27 UTC, s-shpak commented on cmd/staticlint/analyzers/osexit/osexit.go
> +						fn, _ := typeutil.Callee(pass.TypesInfo, x).(*types.Func)
На самом деле тебе не обязательно использовать сторонний пакет: все можно (и лучше) сделать при помощи `ast`. По сути тебе надо найти в синтаксическом дереве вызов функции `main`, внутри которого надо найти вызов `os.Exit`. https://pkg.go.dev/go/ast предоставляет такую возможность

2023-09-05 07:27 UTC, s-shpak commented on README.md
> +(файл ```internal/server/storage/example_sql_test.go```, переменная ```testsDefDSN```).
Это плохая идея: не зашивай переменную для подключения в БД в код, сделай ее параметризуемой

2023-09-05 20:38 UTC, gostuding commented on README.md
> +(файл ```internal/server/storage/example_sql_test.go```, переменная ```testsDefDSN```).
добавил парамет и изменил описание

2023-09-05 21:53 UTC, gostuding commented on cmd/staticlint/analyzers/osexit/osexit.go
> +						fn, _ := typeutil.Callee(pass.TypesInfo, x).(*types.Func)
Основная проблема была в том, как получить имя функции и сравнить его с требуемым string. 
Сначала нашёл как привести её к types.Func и получить имя.
Сейчас переделал без дополнительно пакета.
Исправил алгоритм поиска.

2023-09-05 21:54 UTC, gostuding commented on staticlint
в gitignore

2023-09-06 06:43 UTC, s-shpak approved these changes

2023-09-06 17:50 UTC, merged