Iter23
gostuding/go-metrics pull request #23
Opened 2023-09-15 16:58 UTC by gostuding

2023-09-19 19:23 UTC, s-shpak requested changes
Поправь, пожалуйста, замечания `golangci-lint`

2023-09-21 08:58 UTC, gostuding commented on agent_config.cfg
Поправил

2023-09-21 09:09 UTC, gostuding commented on internal/agent/metrics/functions.go
> +	data = append(data, msg[i:])
Исправил ошибку. 
Странно, что оно работало, ведь я тестировал перед отправкой.

2023-09-21 09:13 UTC, gostuding commented on internal/agent/metrics/functions.go
> +func splitMessage(msg []byte, size int) [][]byte {
Переместил внутрь

2023-09-21 09:20 UTC, gostuding commented on internal/server/middlewares/decript.go
> +func decriptMessage(key *rsa.PrivateKey, msg []byte) (*[]byte, error) {
Поправил.

2023-09-21 13:04 UTC, s-shpak approved these changes
LGTM!

2023-09-21 20:07 UTC, merged