Iter25
gostuding/go-metrics pull request #25
Opened 2023-10-01 19:06 UTC by gostuding

2023-10-02 22:15 UTC, s-shpak requested changes
Очень неплохо! Хотелось бы внести буквально несколько изменений

2023-10-02 22:15 UTC, s-shpak commented on internal/server/interseptors/decriptInterseptor.go
> +	decErrorString  = "decript error: %v"
Я бы не рекомендовал так объявлять сообщение об ошибке: очень просто запутаться с форматированием. Лучше вынести это в отдельную функцию

2023-10-04 20:27 UTC, gostuding commented on internal/server/middlewares/example_test.go
Этот файл убирать не стоит, т.к. в нем содержатся примеры по созданию middlewares, которые отображаются в документации.
Переписал `subnet.go` и добавил тест `subnet_test.go`

2023-10-04 20:28 UTC, gostuding commented on internal/server/interseptors/decriptInterseptor.go
> +	decErrorString  = "decript error: %v"
Переделал

2023-10-04 20:34 UTC, gostuding commented on internal/server/middlewares/subnet.go
> +		fn := func(w http.ResponseWriter, r *http.Request) {
Переделал

2023-10-05 18:19 UTC, s-shpak approved these changes

2023-10-05 19:36 UTC, merged