Iter5
gostuding/go-metrics pull request #5
Opened 2023-05-11 20:32 UTC by gostuding

2023-05-11 23:28 UTC, s-shpak commented on cmd/agent/metrics/runtimemetrics.go
> +	PollCount   int64
Текст задания второго инкремента сформулирован несколько некорректно, метрика `PollCount` на сервере должна отражать реальное количество операций сбора метрик на агенте.  Это не так в текущей реализации

2023-05-11 23:28 UTC, s-shpak commented on cmd/agent/metrics/runtimemetrics.go
> +func (ms MetricsStorage) SendMetrics(address fmt.Stringer) {
Я советую везде использовать один и тот же тип ресивера: если это указатель, `ms *MetricsStorage`, то лучше, если везде будет использоваться указатель

2023-05-11 23:28 UTC, s-shpak commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
Рефлексию лучше не использовать, это дорого

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Не стоит паниковать, лучше вывести сообщение об ошибке и завершить выполнение с ненулевым кодом: `log.Fatal`

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/handlers/handlers.go
> +func MethosNotAllowed(writer http.ResponseWriter, request *http.Request) {
deadcode

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/router.go
> +var memory = storage.MemStorage{}
Не совсем понимаю, зачем делать эту переменную глобальной

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/interfaices.go
`interfaices` -> `interfaces`

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/interfaices.go
> +type Stringer interface {
Зачем переопределять этот интерфейс?

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/interfaices.go
> +type StorageSeter interface {
Интрефейсы должны определяться там, где они используются

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/interfaices.go
> +type Storage interface {
deadcode

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/memStorage.go
Файлы в Go называбтся через snake case

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/memStorage.go
> +// type gauge map[string]float64
Закомментированный код лучше удалить

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/memStorage.go
> +func (ms MemStorage) String() string {
А зачем?

2023-05-11 23:28 UTC, s-shpak commented on cmd/server/storage/memStorage_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `tt` := `tt`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-13 08:22 UTC, gostuding commented on cmd/server/storage/interfaices.go
> +type Stringer interface {
Интерфейс был добавлен на этапе осознания, что такое интерфейс. Далее просто забыл его убрать

2023-05-13 08:25 UTC, gostuding commented on cmd/server/storage/memStorage.go
> +func (ms MemStorage) String() string {
Для вывода содержимого в первом инкременте. Оставил, вдруг понадобится

2023-05-13 08:26 UTC, gostuding commented on cmd/agent/main.go
> +	Storage := new(metrics.MetricsStorage)
new взял из примера в обучении. Учту в дальнейщем

2023-05-13 08:38 UTC, gostuding commented on cmd/agent/flags.go
> +		return 0
Думал наоборот, необходимо использовать значения по умолчанию, чтобы можно было запускать с параметром -a=localhost без указания порта. Поправлю.

2023-05-13 08:47 UTC, gostuding commented on cmd/agent/flags.go
> +
поправил

2023-05-13 08:47 UTC, gostuding commented on cmd/agent/flags.go
> +type NetWorkAdress struct {
поправил

2023-05-13 08:47 UTC, gostuding commented on go.sum
> +github.com/go-chi/chi/v5 v5.0.8 h1:lD+NLqFcAi1ovnVZpsnObHGW4xb4J8lNmoYVfECH1Y0=
сделано

2023-05-13 09:14 UTC, gostuding commented on cmd/agent/main.go
> +	fmt.Println("Args values: ", SendAddress, UpdateTime, SendTime)
поправил

2023-05-13 09:41 UTC, gostuding commented on cmd/agent/metrics/interfaces.go
> +type Storager interface {
Поправил

2023-05-13 10:02 UTC, gostuding commented on cmd/agent/flags.go
> +	n.Port = 8080
поправил

2023-05-13 10:04 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +	PollCount   int64
Понял, просто обнуляю после отправки.

2023-05-13 10:21 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +func (ms MetricsStorage) SendMetrics(address fmt.Stringer) {
Поправил

2023-05-13 10:42 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +				fmt.Printf("Send metric: '%s' error: '%v'\n", name, err)
Переделал

2023-05-13 11:03 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
Тогда как передрать переменные среды runtime, если в документации к runtime (https://pkg.go.dev/runtime) написано, что переменные окружения могут меняться в разных ОС и версиях go? В данном случае статическая привязка переменных не подойдёт, поэтому приходится использовать рефлексию для определения наличия переменных. Возможно я чего-то не понимаю.

> The following environment variables ($name or %name%, depending on the host operating system) control the run-time behavior of Go programs. The meanings and use may change from release to release.

2023-05-13 11:09 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
Также про метрики написано (https://pkg.go.dev/runtime/metrics@go1.20.4), что набор метрик может изменяться по мере развития самой среды выполнения:

> The set of metrics defined by this package may evolve as the runtime itself evolves, and also enables variation across Go implementations, whose relevant metric sets may not intersect.

2023-05-13 11:10 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +			resp, err := client.Post(query, "text/plain", nil)
Переделал на log.Print()

2023-05-13 11:27 UTC, gostuding commented on cmd/agent/runner.go
> +		index += 1
Поправил, хотя схема рабочая была

2023-05-13 11:43 UTC, gostuding commented on cmd/server/main.go
> +		panic(err)
Было взято из уроков, поправил

2023-05-13 12:12 UTC, gostuding commented on cmd/server/router.go
> +var memory = storage.MemStorage{}
Передел.

2023-05-13 12:12 UTC, gostuding commented on cmd/server/storage/interfaices.go
Этот файл больше не нужен

2023-05-13 12:13 UTC, gostuding commented on cmd/server/storage/interfaices.go
> +type Stringer interface {
Переделал

2023-05-13 12:13 UTC, gostuding commented on cmd/server/storage/interfaices.go
> +type StorageSeter interface {
Переделано

2023-05-13 12:14 UTC, gostuding commented on cmd/server/storage/interfaices.go
> +type Storage interface {
Убрано

2023-05-13 12:14 UTC, gostuding commented on cmd/server/storage/interfaices.go
> +type Storage interface {
Убрано

2023-05-13 12:14 UTC, gostuding commented on cmd/server/storage/memStorage.go
Поправил

2023-05-13 12:16 UTC, gostuding commented on cmd/server/storage/memStorage.go
> +// type gauge map[string]float64
Почистил код, оставил только коментарии для понимания процесса

2023-05-13 12:16 UTC, gostuding commented on cmd/server/storage/memStorage.go
> +func (ms MemStorage) String() string {
Удалено

2023-05-13 12:28 UTC, gostuding commented on cmd/server/storage/memStorage_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Поправил

2023-05-13 12:29 UTC, gostuding commented on cmd/agent/flags.go
> +var SendAddress = NetWorkAdress{IP: "", Port: 8080}
исправил

2023-05-13 12:29 UTC, gostuding commented on cmd/agent/flags.go
> +		return 0
исправлено

2023-05-13 12:29 UTC, gostuding commented on cmd/agent/flags.go
> +	update := flag.Int("p", 2, "Update metricks interval")
поправил

2023-05-13 12:30 UTC, gostuding commented on cmd/agent/flags.go
> +			return err
добавил обёртку

2023-05-13 13:02 UTC, s-shpak commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
1. Для разных ОС можно написать разные реализации
2. Для разных версий Go можно обновлять код, собирающий метрики

2023-05-13 14:51 UTC, gostuding commented on cmd/agent/main.go
>  package main
Исправлена структура проекта, в cmd оставлены только main.go файлы и получение необходимых парамтров для запуска сервиса

2023-05-13 14:52 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +// var GaugeType int = 1
удалено

2023-05-13 14:54 UTC, gostuding commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
Не могу понять как сделать (, а ссылку на Пачку не прислали(

2023-05-13 15:57 UTC, gostuding commented on cmd/server/handlers/handlers.go
> +	status, err := storage.Update(chi.URLParam(request, "mType"), chi.URLParam(request, "mName"), chi.URLParam(request, "mValue"))
поправил, добавил агрументы у функции (структуру)

2023-05-13 15:57 UTC, gostuding commented on cmd/server/handlers/handlers.go
> +func PathNotFound(writer http.ResponseWriter, request *http.Request) {
убрал

2023-05-13 15:58 UTC, gostuding commented on cmd/server/handlers/handlers.go
> +func MethosNotAllowed(writer http.ResponseWriter, request *http.Request) {
убрал

2023-05-15 19:00 UTC, s-shpak requested changes

2023-05-16 11:26 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
Переделал на статическую сборку параметров

2023-05-16 11:27 UTC, gostuding commented on internal/agent/flags.go
> +func GetFlags() (NetworkAdress, int, int) {
Исправил, тоже об этом подумал, но почему-то не сделал.

2023-05-16 11:28 UTC, gostuding commented on internal/agent/flags.go
> +		panic(fmt.Sprintf("enviroment value '%s' of '%s' type error: '%s'", str, name, err))
Заменил на ошибку. Проверку наличия ошибок поставил в main.go

2023-05-16 11:30 UTC, gostuding commented on internal/agent/flags.go
> +	if len(items) == 2 {
исправил

2023-05-16 11:34 UTC, gostuding commented on internal/agent/runner.go
> +		time.Sleep(1 * time.Second)
Переделал

2023-05-16 23:16 UTC, s-shpak requested changes

2023-05-16 23:16 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +	if err := send(client, ms.Supplier.Alloc, "Alloc"); err != nil {
Не надо делать столько дупликации кода. Собери метрики в один слайс и отправь их при помощи цикла

2023-05-16 23:16 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +	send := func(client http.Client, value any, name string) error {
Вынеси это в отдельную неэкспортируемую функцию - это улучшит читаемость кода

2023-05-16 23:16 UTC, s-shpak commented on cmd/agent/main.go
> +	storage := &metrics.MetricsStorage{}
Как ты думаешь, что случится при такой инициализации, если `PollInterval` будет меньше, чем `UpdateInterval` ? Как это лучше решить ?

2023-05-16 23:16 UTC, s-shpak commented on internal/agent/flags.go
> +func GetFlags() (AgentRunArgs, error) {
Я понимаю, что тебе интересно было поэксперементировать с разными вариантами парсинга флагов, но это слишком сложный код для такого простого use-case'а. Тут два варианта:
1. либо попробуй сделать его по подобию аналогичного кода для сервера
2. либо оставь как есть, но есть вероятность, что в следующих спринтах придется менять

2023-05-16 23:16 UTC, s-shpak commented on internal/server/router.go
> +	router.Get("/value/{mType}/{mName}", func(w http.ResponseWriter, r *http.Request) {
Не очень правильно, что в хендлер передается `metricsArgs`, когда `mValue` здесь невалиден

2023-05-16 23:16 UTC, s-shpak commented on internal/server/handlers.go
> +	if err != nil {
Ошибку стоит логировать, только если она неожидаема. Сейчас `storage` возвращает только `BadRequest`, потому логировать ошибку здесь не стоит

2023-05-16 23:16 UTC, s-shpak commented on internal/server/handlers.go
> +	writer.Write([]byte(value))
Тут ошибку стоит проверить

2023-05-16 23:16 UTC, s-shpak commented on internal/server/handlers.go
> +	writer.Write([]byte(storage.GetMetricsHTML()))
Тут ошибку стоит проверить

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +			return http.StatusBadRequest, err
Это придется менять в дальнейшем, но пока оставим как есть (т.к. не проходили): неправильно, что `storage` знает что-то о `http` запросах

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +		log.Printf("Update metric error. Metric's type incorrect. Type is: %s\n", mType)
Не надо логировать ожидаемую ошибку

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +		fmt.Printf("Gauge metric not found by name: %s\n", mName)
Не надо логировать ожилаемую ошибку (тем более через `fmt.Printf`)

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +	if mType == "gauge" {
Я бы рекомендовал заменить `if-else if` на `switch-case`

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +	if ms.Gauges == nil {
Почему бы не проинициализировать один раз в конструкторе?

2023-05-16 23:16 UTC, s-shpak commented on internal/server/storage/mem_storage_test.go
> +	for _, tt := range tests {
Здесь тоже нужно `tt := tt`

2023-05-16 23:16 UTC, s-shpak commented on cmd/agent/metrics/runtimemetrics.go
> +	fields := reflect.VisibleFields(reflect.TypeOf(ms.Supplier))
1. Ты сделал почти верно, только надо развязать процесс сбора метрик и их отправки
2. О какой ссылке на пачку идет речь?

2023-05-17 08:50 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +	if ms.Gauges == nil {
Можно и в отдельном конструкторе, но тогда нужно сделать структуру не экспортируемой, чтобы нельзя было получить структуру напрямую (&storage.MemStorage{}), иначе произойдёт ошибка. 
Данный вариант считаю наиболее подходящим, т.к. не нужно писать дополнительную функцию конструктор и помнить, что MemStorage обязательно необходимо получать через конструктор. Структура сама посмотрит нужно ей инициализироваться или нет.

2023-05-17 09:02 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +	if mType == "gauge" {
Отголоски Python3, сейчас с на нем наибольшее время пишу, поэтому даже и не подумал про switch.

2023-05-17 09:03 UTC, gostuding commented on internal/server/storage/mem_storage_test.go
> +	for _, tt := range tests {
Исправил

2023-05-17 09:09 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +		fmt.Printf("Gauge metric not found by name: %s\n", mName)
При написании проверял работу сервера и выводил в консоль значения. Забыл убрать.
Исправил

2023-05-17 09:10 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +			return http.StatusBadRequest, err
ok

2023-05-17 09:13 UTC, gostuding commented on internal/server/handlers.go
> +	writer.Write([]byte(storage.GetMetricsHTML()))
Дак если storage.GetMetricsHTML() не может вернуть ошибку, только string? Какую ошибку тогда проверять?

2023-05-17 09:59 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	send := func(client http.Client, value any, name string) error {
Исправил

2023-05-17 10:13 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	if err := send(client, ms.Supplier.Alloc, "Alloc"); err != nil {
Исправил

2023-05-17 10:34 UTC, gostuding commented on cmd/agent/main.go
> +	storage := &metrics.MetricsStorage{}
Ничего страшного не произойдёт, будут отправляться нулевые значения на сервер до момента их считывания. 
Если необходимо запретить такого рода действия, то можно использовать два варианта:
1. проверка что PollInterval не меньше UpdateInterval при валидации флагов и переменых окружения (agentArgs.validate()) и выводить ошибку.
2. Проверка при отправке данных на сервер переменную PollCount, которая хранит количество обновлений за интервал и отправлять данные только если есть обновления ( != 0).
В условии к спринту про это ничего не сказано, поэтому данного рода проверку не добавлял.

2023-05-19 08:48 UTC, s-shpak requested changes

2023-05-19 08:48 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +	if ms.Gauges == nil {
В Go это является негласным соглашением - если существует конструктор, то предполагается, что пользователь пакета не будет использовать `&storage.MemStorage{}`. Лучше сократить здесь проверку на `nil`, т.к. это делает код более эффективным (-1 проверка) и читаемым (не надо задумываться, почему `ms.Gauges` может быть `nil` во время выполнения программы).

2023-05-19 08:48 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +		return fmt.Errorf("metric '%s' type indefined: '%v'", name, v2)
Так это работать не будет: https://go.dev/play/p/sABUsX16fLE

Лучше убрать инициализацию `v2` и при генерации ошибки получать тип через `fmt.Printf("%t", value)`

2023-05-19 08:48 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +	defer resp.Body.Close()
А что если сервер отправил `BadRequest` ? Ошибки не будет, но метрика не отправится на сервер. В случае `PollCount` это приведет к неправильной работе агента. Я бы в случае неожиданного статуса отправлял бы ошибку наверх

2023-05-19 08:48 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func getSortedxKeysFloat(items map[string]float64) []string {
```suggestion
func getSortedKeysFloat(items map[string]float64) []string {
```

2023-05-19 08:48 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *MemStorage) GetMetricsHTML() string {
В дальнейшем, скорее всего, придется вынести это из пакета storage - кажется, что формированием представления данных должен заниматься не он

2023-05-19 16:35 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +func getSortedxKeysFloat(items map[string]float64) []string {
ПОправил

2023-05-19 16:42 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +		return fmt.Errorf("metric '%s' type indefined: '%v'", name, v2)
Исправил

2023-05-19 17:21 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	defer resp.Body.Close()
Об этом совсем не подумал. Исправил, добавил проверку StatusCode ответа

2023-05-19 18:03 UTC, s-shpak commented on internal/server/storage/mem_storage.go
> +func (ms *MemStorage) GetMetricsHTML() string {
Не, не обязательно

2023-05-19 18:05 UTC, s-shpak approved these changes

2023-05-28 14:32 UTC, merged