Iter9
gostuding/go-metrics pull request #9
Opened 2023-05-25 15:30 UTC by gostuding

2023-05-29 13:14 UTC, s-shpak requested changes
Пожалуйста, сделай ребейз ветки, чтобы в этот PR попадали изменения только второго спринта

2023-05-29 13:14 UTC, s-shpak commented on internal/server/runner.go
> +			case syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT:
Не совсем понимаю, зачем этот свитч: сообщение и так придет только от сигналов, описанных выше

2023-05-29 13:14 UTC, s-shpak commented on internal/server/handlers.go
> +		writer.WriteHeader(http.StatusBadRequest)
Я советую стараться меньше исползовать `else`: часто из функции можно выйти значительно раньше, что упрощает код

2023-05-29 13:14 UTC, s-shpak commented on internal/server/handlers.go
> +		_, err = writer.Write([]byte(err.Error()))
Это опасно: если будет возвращена внутренняя ошибка сервиса, то сообщение о ней попадет клиенту, что не безопасно. К тому же Internal Server Error не логгируется

2023-05-29 13:14 UTC, s-shpak commented on internal/server/handlers.go
> +		_, err = writer.Write([]byte(err.Error()))
Это внутренняя ошибка, ее нельзя отправлять клиенту

2023-05-29 13:14 UTC, s-shpak commented on internal/server/handlers.go
> +	} else {
Код можно сделать более плоским

2023-05-29 13:14 UTC, s-shpak commented on internal/server/router.go
> +	// router.Use(middleware.RealIP)
Комменты надо убирать

2023-05-29 13:14 UTC, s-shpak commented on internal/server/middleware.go
> +	wrapper := func(w http.ResponseWriter, r *http.Request) {
Зачем создавать новую переменную здесь? Просто оберни эту логику `http.HandlerFunc`

2023-05-29 13:14 UTC, s-shpak commented on internal/server/middleware.go
> +		if strings.Contains(r.Header.Get("Content-Encoding"), "gzip") { // если стоит gzip, то надо распаковывать
Логика middleware для компрессии и для логгирования должна быть разнесена

2023-05-29 19:12 UTC, gostuding commented on internal/agent/flags.go
> +		send, err := strToInt("REPORT_INTERVAL", upd)
Не совсем понял про что именно идёт речь. Поправил названия переменных.

2023-05-29 19:15 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +			return err
Добавил обёртку fmt.Errorf(...)

2023-05-29 19:16 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	return &MetricsStorage{MetricsSlice: make(map[string]Metrics, 0)}
Поправил

2023-05-29 19:21 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	PollCount    int64
Убрано

2023-05-29 19:21 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	RandomValue  float64
+

2023-05-29 19:48 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	return Metrics{}
Поправил

2023-05-29 19:48 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +		val, _ := strconv.Atoi(fmt.Sprint(value))
Добавил проверку

2023-05-29 19:49 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	"github.com/dpanic/convert"
Убрал

2023-05-29 22:49 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	ms.MetricsSlice["Alloc"] = makeMetric("Alloc", runtimeMetrics.Alloc)
Переделал для цикла, добавил функцию формирования map, по ней формируется MetricsSlice с добавлением значений типа gauge для тех, которые изначально counter. В цикле проверяется на ошибки конвертирования

2023-05-29 23:08 UTC, gostuding commented on internal/server/middleware.go
> +		if strings.Contains(r.Header.Get("Content-Encoding"), "gzip") { // если стоит gzip, то надо распаковывать
Поправил

2023-05-29 23:13 UTC, gostuding commented on internal/server/handlers.go
> +		_, err = writer.Write([]byte(err.Error()))
Поправил

2023-05-29 23:18 UTC, gostuding commented on internal/server/router.go
> +	// router.Use(middleware.RealIP)
Поправил

2023-05-29 23:19 UTC, gostuding commented on internal/server/storage/mem_storage.go
> +// #TODO - сделать структуру не экспортируемой
Удалил

2023-05-29 23:22 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +			log.Println(err)
Поправил

2023-05-29 23:37 UTC, gostuding commented on internal/server/flags.go
> +	case "false":
Не согласен, при такой логике, произойдет нарушение условия для инкремента , в котором сказано, что значение restore по-умолчанию равно true! Если применить `case "false", "":` то при считывании переменной окружения `os.Getenv("RESTORE")`  будет возвращаться пустое значение и переменная примет значение false.  Проверку на пустое значение всё-равно необходимо делать, чтобы избежать ситуации когда RESTORE не определена в окружении.

2023-05-29 23:38 UTC, gostuding commented on internal/server/flags.go
> +			return nil, errors.New("enviroment RESTORE error. Use 'true' or 'false' value")
Добавил в описание ошибки

2023-05-29 23:38 UTC, gostuding commented on cmd/server/main.go
> +			fmt.Println("asdasds")
Убрано

2023-05-29 23:39 UTC, gostuding commented on cmd/server/main.go
> +		if err := recover(); err != nil {
Осталось от поиска перехвата Ctrl+C для консоли, забыл убрать

2023-05-30 19:36 UTC, gostuding commented on internal/agent/flags.go
> +			return agentArgs, fmt.Errorf("enviroment 'ADDRESS' value error: %s", err)
Поправил

2023-05-30 20:35 UTC, gostuding commented on internal/server/middleware.go
> +	wrapper := func(w http.ResponseWriter, r *http.Request) {
Поправил

2023-05-30 20:35 UTC, gostuding commented on internal/server/middleware.go
> +		if strings.Contains(r.Header.Get("Content-Encoding"), "gzip") { // если стоит gzip, то надо распаковывать
Разделил логику

2023-05-30 21:10 UTC, gostuding commented on internal/server/handlers.go
> +		_, err = writer.Write([]byte(err.Error()))
Убрал запись ошибки клиенту

2023-05-30 21:45 UTC, gostuding commented on internal/server/runner.go
> +			case syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT:
Переделал

2023-05-30 21:46 UTC, gostuding commented on internal/server/runner.go
> +	Logger.Infoln("Run server at adress: ", options.IPAddress)
Исправил

2023-05-30 21:47 UTC, gostuding commented on internal/server/runner.go
> +var currentOptions ServerOptions
Убраны

2023-05-30 21:49 UTC, gostuding commented on cmd/server/main.go
> +		panic(err)
Дак это же настройки! Если изначально настройки неправильные, то работать не будет. Если не паниковать, то что делать? Создавать настройки по-умолчанию?

2023-05-30 22:08 UTC, gostuding commented on internal/agent/flags.go
> +type AgentRunArgs struct {
Переименовал

2023-05-30 22:09 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	log.Println("Metrics send iteration finished")
Поправил

2023-05-30 22:09 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	log.Println("Update finished")
Поправил

2023-05-30 22:09 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	"log"
Добавил zap

2023-05-30 22:10 UTC, gostuding commented on go.mod
Обновил

2023-05-31 23:42 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
`log.Fatal` логгирует ошибку и вызывает `os.Exit(1)`

2023-05-31 23:50 UTC, s-shpak requested changes

2023-05-31 23:50 UTC, s-shpak commented on internal/server/flags.go
> +	case "false":
согласен

2023-05-31 23:50 UTC, s-shpak commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Глобальные переменные не нужны. Используй везде либо один и тот же логгер, либо логгеры, порожденные от одного базового логгера

2023-05-31 23:50 UTC, s-shpak commented on internal/server/router.go
> +	router.Use(middleware.RealIP)
Можно передать все middleware в один `Use`

2023-06-01 10:05 UTC, gostuding commented on cmd/server/main.go
> +		panic(err)
Исправил

2023-06-01 10:06 UTC, gostuding commented on internal/server/router.go
> +	router.Use(middleware.RealIP)
Переделал в одни Use

2023-06-01 11:20 UTC, gostuding commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Переделал.
Не сосвсем понятно почему нельзя сделать логер глобальным? При использовании в middleware очень удобно если логер глобальный. Его можно сделать не экспортируемым, т.е. только для модуля. Иначе приходится создавать логер и проверять на ошибку при каждом запросе от клиента, т.к.не могу понять  как передать объект логера внутрь Use(... func(http.Heandler) http.Heandler).

2023-06-04 11:34 UTC, s-shpak commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Это может быть удобным, пока код небольшой. Когда он начинает разрастаться неявные зависимости, меняющие состояние программы, - путь к проблемам

К примеру, можно передать логгер через поле структуры, через которую ты можешь вызывать middleware

2023-06-04 11:45 UTC, s-shpak requested changes

2023-06-04 11:45 UTC, s-shpak commented on internal/server/handlers.go
> +	} else {
Этот `else` можно убрать, чтобы сделать код более плоским

2023-06-04 11:45 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Не вижу в этом PR: переименую PR, которы ты создал, чтобы вмерджить именно `iter9` в `main` - это правила

2023-06-04 11:45 UTC, s-shpak commented on internal/server/middleware.go
> +		logger, err := InitLogger()
не надо инициализировать второй логгер

2023-06-04 11:45 UTC, s-shpak commented on internal/server/middleware.go
> +		start := time.Now()
Таймер лучше стартовать перед вызовом хендлера

2023-06-04 11:45 UTC, s-shpak commented on internal/server/storage/mem_storage_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Надо добавить перед этим вызовом

```go
tt := tt
```

2023-06-04 14:25 UTC, gostuding commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Зачем такой геморой!? Что за супер проект должен быть, что логгер может привести к проблемам? Как он меняет состояние системы? Про что здесь вообще речь идет?

2023-06-04 14:27 UTC, gostuding commented on internal/server/middleware.go
> +		start := time.Now()
и в чём разница?

2023-06-04 14:42 UTC, gostuding commented on internal/server/handlers.go
> +	} else {
те же яйца, только сбоку

2023-06-04 20:03 UTC, s-shpak commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Это хорошие вопросы, но на них довольно сложно ответить в рамках ревью. Либо пиши в пачку в общий чат, либо возьми 1-1

2023-06-04 20:04 UTC, s-shpak commented on internal/server/middleware.go
> +		start := time.Now()
Разница в том, что мы измеряем время выполнения хегдлера, а не логики middleware

2023-06-04 20:12 UTC, s-shpak commented on internal/server/handlers.go
> +	} else {
см https://app.pachca.com/chats/5796540?message=56748863

2023-06-04 21:58 UTC, s-shpak requested changes

2023-06-04 21:58 UTC, s-shpak commented on internal/server/middleware.go
> +		start := time.Now()
То что ты сделал неверно: тебе не надо стартовать таймер в замыкании - так он запустится только один раз, при выполнении функции. Таймер надо запускать каждый раз при обработке запроса, предыдущий вариант был почти правильным, только старт таймера надо было перенести на строку перед `next.ServeHTTP`

2023-06-05 06:16 UTC, gostuding commented on internal/server/handlers.go
> +	} else {
Переделано

2023-06-05 06:18 UTC, gostuding commented on internal/server/middleware.go
> +		logger, err := InitLogger()
Логер передаётся в middleware через функцию. Решение сделано по аналогии с `func RequestLogger(f LogFormatter) func(next http.Handler) http.Handler ` пакета `github.com/go-chi/chi/middleware`

2023-06-05 06:22 UTC, gostuding commented on internal/server/middleware.go
> +		logger, err := InitLogger()
Логер передаётся в middleware через функцию. Решение сделано по аналогии с `func RequestLogger(f LogFormatter) func(next http.Handler) http.Handler ` пакета `github.com/go-chi/chi/middleware`

2023-06-05 06:27 UTC, gostuding commented on internal/server/middleware.go
> +		start := time.Now()
Теперь понятно. Замеряем только выполнение запроса без учёта внутреннего дейвства данного middleware. 
Исправил

2023-06-05 06:32 UTC, gostuding commented on internal/server/logger.go
> +var Logger *zap.SugaredLogger = zap.NewNop().Sugar()
Глобальные переменные убраны.

2023-06-05 20:59 UTC, s-shpak requested changes

2023-06-05 20:59 UTC, s-shpak commented on internal/agent/metrics/runtimemetrics.go
> +	logger, err := zap.NewDevelopment()
Лучше везде передавать корневой логгер: тот, который ты инициализировал в main. Еще круче будет "отпочковывать" логгер от корневого при передаче в компонент, но это не обязательно

2023-06-06 19:25 UTC, gostuding commented on cmd/server/main.go
> +		panic(err)
заменил panic(err) на log.Fatalln(err)

2023-06-06 19:26 UTC, gostuding commented on internal/agent/metrics/runtimemetrics.go
> +	logger, err := zap.NewDevelopment()
Переделал, логер передаётся из main

2023-06-06 19:42 UTC, gostuding commented on internal/agent/flags.go
> +		send, err := strToInt("REPORT_INTERVAL", upd)
Вынес проверку переменных окружения REPORT_INTERVAL и POLL_INTERVAL в отдельные функции.

2023-06-07 11:56 UTC, s-shpak approved these changes

2023-06-07 16:34 UTC, merged